name: Predixa AI Autobot

on:
  schedule:
    # Berjalan setiap hari Senin sampai Jumat pada jam 09:00 UTC (Sama dengan 16:00 WIB, tepat saat pasar saham tutup)
    - cron: '0 9 * * 1-5'
  
  # Memungkinkan kamu menjalankan bot secara manual dari tombol di website GitHub
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Library Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_bot.txt

      - name: Jalankan Bot Prediksi
        run: python bot_telegram.py
